CREATE TABLE targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid INT NOT NULL,
    display_name VARCHAR(100),
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_id BIGINT NOT NULL,
    captured_at TIMESTAMP NOT NULL,

    heap_used BIGINT NOT NULL,
    heap_committed BIGINT NOT NULL,
    heap_max BIGINT NOT NULL,

    meta_used BIGINT NOT NULL,
    meta_committed BIGINT NOT NULL,

    thread_count INT NOT NULL,
    runnable_count INT NOT NULL,
    blocked_count INT NOT NULL,
    waiting_count INT NOT NULL,

CONSTRAINT fk_snapshots_target FOREIGN KEY (target_id) REFERENCES targets(id)
);

CREATE INDEX idx_snapshots_target_captured_at ON snapshots(target_id, captured_at);